name: Android CI & Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本号，例如 1.0.1'
        required: true
      release_notes:
        description: 'Release 说明'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3. Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools-version: '34.0.0'

      # 4. Install Gradle CLI (8.2)
      - name: Set up Gradle CLI
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.2'
          cache-disabled: true
          # wrapper: false  # 默认不使用 wrapper

      # 5. Verify theme XML files
      - name: Verify theme files
        run: |
          echo "values/ 目录内容："
          ls -1 app/src/main/res/values
          for f in attrs.xml colors.xml themes.xml; do
            test -f app/src/main/res/values/$f || (echo "ERROR: 缺少 $f" && exit 1)
          done

      # 6. Verify & copy icons
      - name: Copy custom icons
        run: |
          echo "icons/ 目录结构："
          ls -R icons || (echo "ERROR: icons/ 不存在" && exit 1)

          echo "删除默认 mipmap*"
          rm -rf app/src/main/res/mipmap-*/

          echo "拷贝自定义 icons → app/src/main/res/"
          cp -rv icons/mipmap-* app/src/main/res/
          echo "Res 下已存在 mipmap*："
          ls -1 app/src/main/res | grep mipmap || (echo "ERROR: 无 mipmap* 目录" && exit 1)

      # 7. Compile Kotlin only, capture errors
      - name: Compile Kotlin & capture errors
        shell: bash
        run: |
          echo ">>> Listing values/"
          ls -R app/src/main/res/values

          echo ">>> Kotlin compile start"
          gradle --no-daemon clean compileDebugKotlin compileReleaseKotlin \
            --console=plain --info --stacktrace 2>&1 | tee compile.log

      # 8. Upload compile.log on failure
      - name: Upload kotlin-compile-log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: kotlin-compile-log
          path: compile.log

      # 9. Build Debug & Release APKs, capture full logs
      - name: Build Debug & Release APKs
        shell: bash
        run: |
          echo ">>> Assemble APKs"
          gradle --no-daemon assembleDebug assembleRelease \
            --console=plain --info --stacktrace 2>&1 | tee build.log

      # 10. Upload build.log on failure
      - name: Upload full-build-log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: full-build-log
          path: build.log

      # 11. Create GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.release_notes }}

      # 12. Upload Debug APK
      - name: Upload Debug APK
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: IClash-${{ github.event.inputs.version }}-debug.apk
          asset_content_type: application/vnd.android.package-archive

      # 13. Upload Release APK
      - name: Upload Release APK
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/release/app-release.apk
          asset_name: IClash-${{ github.event.inputs.version }}-release.apk
          asset_content_type: application/vnd.android.package-archive