name: Android CI & Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本号，例如 1.0.1'
        required: true
      release_notes:
        description: 'Release 说明'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - uses: actions/checkout@v4

      # 2. Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3. Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools-version: '34.0.0'

      # 4. Copy custom icons into res/
      - name: Copy icons into res
        run: |
          cp -r icons/mipmap-* app/src/main/res/

      # 5. Build with Gradle Build Action (无需本地 gradlew)
      - name: Build Debug & Release APKs
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ':app:assembleDebug :app:assembleRelease --stacktrace'

      # 6. Create GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.release_notes }}
          draft: false
          prerelease: false

      # 7. Upload Debug APK
      - name: Upload Debug APK
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: IClash-${{ github.event.inputs.version }}-debug.apk
          asset_content_type: application/vnd.android.package-archive

      # 8. Upload Release APK
      - name: Upload Release APK
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/release/app-release.apk
          asset_name: IClash-${{ github.event.inputs.version }}-release.apk
          asset_content_type: application/vnd.android.package-archive