name: Android CI & Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本号，例如 1.0.1'
        required: true
      release_notes:
        description: 'Release 说明'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 签出代码
      - uses: actions/checkout@v4

      # 2. 校验主题资源文件
      - name: Verify theme files
        run: |
          echo "Checking app/src/main/res/values:"
          ls -1 app/src/main/res/values
          for f in attrs.xml colors.xml themes.xml; do
            test -f app/src/main/res/values/$f \
              || (echo "ERROR: $f is missing!" && exit 1)
          done

      # 3. 校验 icons 目录
      - name: Verify icons folder
        run: |
          echo "icons/ structure:"
          ls -R icons \
            || (echo "ERROR: icons/ not found!" && exit 1)

      # 4. 删除默认 mipmap 目录
      - name: Clean default mipmaps
        run: rm -rf app/src/main/res/mipmap-*/

      # 5. 拷贝自定义 icons（输出详情）
      - name: Copy custom icons
        run: |
          echo "Copying icons into res/"
          cp -rv icons/mipmap-* app/src/main/res/
          echo "Resulting mipmap folders:"
          ls -1 app/src/main/res | grep mipmap \
            || (echo "ERROR: no mipmap folders found!" && exit 1)

      # 6. 设置 JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 7. 设置 Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools-version: '34.0.0'

      # 8. 只编译 Kotlin 并捕获错误
      - name: Compile Kotlin & capture errors
        shell: bash
        run: |
          echo ">>> Listing values/ before Kotlin compile"
          ls -R app/src/main/res/values
          echo ">>> Starting Kotlin compile"
          ./gradlew clean compileDebugKotlin compileReleaseKotlin \
            --console=plain --info --stacktrace 2>&1 | tee compile.log

      # 9. 如果 Kotlin 编译失败，上传日志
      - name: Upload kotlin-compile-log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: kotlin-compile-log
          path: compile.log

      # 10. 真正组装 APK（只有在 Kotlin 编译通过后执行）
      - name: Build Debug & Release
        shell: bash
        run: |
          echo ">>> Assembling APKs"
          ./gradlew assembleDebug assembleRelease \
            --console=plain --info --stacktrace 2>&1 | tee build.log

      # 11. 构建失败时上传完整 build.log
      - name: Upload build.log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: full-build-log
          path: build.log

      # 12. 创建 GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.release_notes }}

      # 13. 上传 Debug APK
      - name: Upload Debug APK
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: IClash-${{ github.event.inputs.version }}-debug.apk
          asset_content_type: application/vnd.android.package-archive

      # 14. 上传 Release APK
      - name: Upload Release APK
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/release/app-release.apk
          asset_name: IClash-${{ github.event.inputs.version }}-release.apk
          asset_content_type: application/vnd.android.package-archive